language: java

jdk:
- oraclejdk7
- oraclejdk8

branches:
   except:
     - gh-pages

env:
  global:
    - secure: dOgVzml0sqa7ekF/7LO+W9RhbLI5L5wE+X421dyJaFGVhdD3PKVoKDMn8K5p0Dn5l/4oOQ/y3dWuOS35G+dXwrAOHPOBYq+/gPy8jfq0cfPR1hYI+s2qivw3DFp92Oqsk7fo7o22nFylWoaCQUQzRJKctanyKJIZV+tw3uPC0F1AAzoHW1d1Gp0STkgD3p5pEAbQv6vGOtlSKl7ErmD2XQEG8+0GO4UWEqopVycECBBC5UGDvJvMdO3qoKLv2fA1SuUcvlviTRsXK7Qv9xW/eLziM0m/GTDOpRjIxNqMLUY0o/M6+6CdhoyGstH5hBggF0yADZlGPb/24cj1nEtGm/8c8zfxyNFP5aXbV2HrFA8YtGIiZ8qgTiadxhjzDRCEtXpxh55FTa8uTOy7yNvsT62vYiSHBzIq9SAph6/HxzRbbEOxoU6pEG8r3wIfiHaMz4aH++1hKTtbRC+FvV0gd84PlGH3GO1UesyaIZiupnsu6JDaK+oZPMKy3ngFxOeSfEJrp3au8iQKgdWEtzklrFBtOK61eUlCS7MBcr5EJ76ih563RelGUf+4Ky1Cdy16FNfuuBfXgaa5iAmPCPc1vNsNpGLRrkT+wPN/XgMi9/pIuwNwfgwX75NVzY0K9x3CyrZ0wRyYr/H6KREPpMoM5bZkDjmpKnGAJQpvwK4ZENM=
    - secure: swPmHlLuXv3glEOxyty1iC9sUxtEFJ4Ebw+0skH+tC0BRepRWYvodL08zIBjmE6pXuyTGvbociCEbmYGcHozlJaBgtpPajJQT/dT3P75+u7JDHnv9rHbfF/K5RIksKuuNyXVIHA8NjY+LgkqCkx0YVjpHtCJJYRKbH2ktdZHJDJfjULBDfKn96x+eVYCbXYlmqPLwDQRUHXrzBhPar1VVQk4Rw3J6XoYRlIThPO5MMf5Ohuy6/H1DBnUBOGspSHIErUtcyYHtJ6O0HuEvIICQlTVciPluXtCx8mL/BRufkpxtUHnuXe4aqw+33va+pqlGQlyW8C+pt/Ztm0AXG1a4z1hzJ6xyo8l9WzRXkLPp/J+3/fepVYkMotaYNvQNXusjLyDuuc0MNza9oYPSPxDZLfFBsgimEk2JAAU8BZckVSJvziqBdX/vcMAH3s3D/IT6LlaXarh333w8YCfT0Ua3VwrYz4Iuk/4GukLiM6+9Vcv/ANOrWbNFyUqeINqe9VV6vzBErpO1pqfMPU6UA7vtaUv0lRIldvQHGJ73y3bMGZvxCjxenLdBWzC2+LJFKi1plOU0/kC9Bjf1lnp4s9HLCes9COBAoqFOtU7WEzQ81rj0eATxt8EM7q1mMzb21zF4YzuOgDCMQtiQZOR4OYiH+MTABmMt6OQrdFtSaXKuPs=

after_success:
  - .buildscript/deploy_snapshot.sh

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2

